### ISSUE TITLE
Jackbox controller 5.22.0

### ISSUE THREAD

**Issue by poo-sky** [jackbox-int/jackbox-int.github.io#2]
https://github.com/jackbox-int/jackbox-int.github.io The archive with the controller is damaged, when you open the file index.html site hangs, or in other words it loads endlessly. The download of the zip file stops at 254 megabytes.

**Comment by BurAndBY** [comment]
Works fine for me, also you need a webserver to use the website. Try forking the repo and use [Vercel](https://vercel.app/)

**Comment by poo-sky** [comment]
> Works fine for me, also you need a webserver to use the website. Try forking the repo and use [Vercel](https://vercel.app/)


I can't open in offline on computer

**Comment by BurAndBY** [comment]
> > Works fine for me, also you need a webserver to use the website. Try forking the repo and use [Vercel](https://vercel.app/)
> 
> 
> I can't open in offline on computer

You wasn't able to open it offline since 4.2.0
