### ISSUE TITLE
"Unable to load" error caused by updating files

### ISSUE THREAD

**Issue by mirkoixd** [jackbox-int/jackbox-int.github.io#3]
Each time I update files, website gives "unable to load" error

![image](https://user-images.githubusercontent.com/63493286/194172648-263a8890-e922-4904-b58b-77f93a52cfc9.png)
![image](https://user-images.githubusercontent.com/63493286/194171872-3fbc2922-6b29-41dc-85eb-d170f865bc8a.png)

`function y_(){"console"in H&&rr.forEach(function(t){t in H.console&&se(H.console,t,function(e){return function(...r){Ee("console",{args:r,level:t}),e&&e.apply(H.console,r)}})})}`

But, when I turned on VPN, website was working until I pressed "Ctrl+F5"
Don't really know what's wrong.

**Comment by BurAndBY** [comment]
I'm able to reload and work perfectly with the original website. Can you link yours so we can troubleshoot?

**Comment by BurAndBY** [comment]
Also do you run the website using a webserver? Might be related to #2

**Comment by mirkoixd** [comment]
Yes. I'm using personal server. It's not offline, because it worked before any updates were added.
Webstie: https://tg.jackbox.ru/

**Comment by BurAndBY** [comment]
So, the website you linked is the 3.1.16, but the version we are talking about is 5.0.0+. Also did you port the update manually or just pasted tons of code?

**Comment by BurAndBY** [comment]
Also I don't think Whitey's version is compatible with DarkSid3r's

**Comment by mirkoixd** [comment]
...
Right now it's on 3.1.16, because 5.35.0+ doesn't work properly...

**Comment by mirkoixd** [comment]
Actually, I already solved the problem. It was caused by using cloudfare.
